### ISSUE TITLE
Need for a config came quicker than I thought.

### ISSUE THREAD

**Issue by lobes** [lobes/smoko#2]
We all knew this day would come, where we read from `{$HOME/.config/smoko/config.toml}` into a `config struct`.

Taking suggestions for what should be in here.

## Defaults
```toml 
# ~/.config/smoko/config.toml
run_in_background = false # defaults to displaying a countdown timer
input_block_time = 30 # :float (sec) 
                      # how long do you want smoko to block keyboard and mouse input once smoko triggered
```
